# Generated by Django 4.0.1 on 2022-07-18 08:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_product_desciption_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=datetime.date(2022, 7, 18)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
